logging:
  level:
    org:
      springframework:
        web: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_web
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:database/liquibase-changelog.xml
    contexts: prod